### ISSUE TITLE
Add [+], [-] button to adjust grinder setting among known values

### ISSUE THREAD

**Issue by EddieHyun** [hsyhsw/de1app_plugin_DYE#1]

**Comment by EddieHyun** [comment]
![image](https://user-images.githubusercontent.com/7153666/204909952-e0f4aa81-6385-48cf-b6fa-86b2fdf25f69.png)
up, down button added next to the grinder setting selector

**Comment by hsyhsw** [comment]
seems.... O..K..?
Tested a few times, with no issue found.

**Comment by EddieHyun** [comment]
![image](https://user-images.githubusercontent.com/7153666/205012270-05e564ed-660d-4e43-b37b-51c013cd41be.png)
- Arrow buttons are now black&white.
- Numeric settings are sorted (if not, it follows `ORDER BY grinder_setting` clause)
